---
# tasks file for musicstorefrontend

# - shell: node -v
#   register: shellout2
# - debug: var=shellout2.stdout

# - name: install npm
  # apt:
  #   name: npm
  #   state: present

# - name: Install Angular.js
#   npm:
#     name: "@angular/cli"
#     global: yes
#     state: present

- name: Install nginx server
  apt: 
    name: nginx
    state: latest
- name: Removing default file from sites_available
  file:
    path: /etc/nginx/sites-available/default
    state: absent
- name: Removing default file from sites_enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: Copy config file in sites available
  copy:
    src: ./files/code
    dest: /etc/nginx/sites-available/code
- name: Create symlink
  file:
    src: /etc/nginx/sites-available/code
    dest: /etc/nginx/sites-enabled/code
    state: link

# - name : Copy local url ts file in files folder
#   copy:
#     src: "{{playbook_dir}}/../terraform/deployments/local_url.ts"
#     dest: "{{role_path}}/files/"

- name : Copy local url ts file in files folder
  local_action: ansible.builtin.command cp {{playbook_dir}}/../terraform/deployments/local_url.ts {{role_path}}/files/

- name : Copy local url ts file in angular folder
  local_action: ansible.builtin.command cp {{role_path}}/files/local_url.ts {{playbook_dir}}/../NewMusicStoreFrontEnd/src/dto/

# - name : Copy local url ts file in angular folder
#   copy:
#     src: "{{role_path}}/files/local_url.ts"
#     dest: "{{playbook_dir}}/../NewMusicStoreFrontEnd/src/dto/"


# - name: Copy ts file to angualar frontend directory
#   copy:
#     src: ./files/local_url.ts
#     dest: ../../../NewMusicStoreFrontEnd/src/dto/local_url.ts

# - shell: pwd
#   register: shellout2
# - debug: var=shellout2.stdout


  #- name: Run ng build
  #shell: "npm run prod-build --prefix {{playbook_dir}}/../NewMusicStoreFrontEnd/"
  
- name: ng build command
  local_action: ansible.builtin.command npm run prod-build --prefix {{playbook_dir}}/../NewMusicStoreFrontEnd/ 
  # shell: npm run prod-build --prefix .
  # 
  # args:
  #   chdir: "{{playbook_dir}}/../NewMusicStoreFrontEnd/"

# - name : Copy Music Store folder in files directory
#   copy:
#     src: "{{playbook_dir}}/../NewMusicStoreFrontEnd/dist/MusicStore"
#     dest: "{{role_path}}/files/"

- name: Copy Music Store folder in files directory
  local_action: ansible.builtin.command cp -r {{playbook_dir}}/../NewMusicStoreFrontEnd/dist/MusicStore {{role_path}}/files/
 

- name: copy index.html file
  copy:
    src: "{{role_path}}/files/MusicStore"
    dest: /var/www/

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Restart nginx
  service:
    name: nginx
    state: restarted


